import { Product } from './store'

export const products: Product[] = [
  {
    id: '1',
    name: 'Eternal Diamond Ring',
    price: 4999,
    originalPrice: 5999,
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=80',
      'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800&q=80',
    ],
    category: 'Rings',
    collection: 'Eternal',
    description: 'A stunning solitaire diamond ring set in 18k white gold. Perfect for engagements or special occasions.',
    details: ['18k White Gold', '1.5 Carat Diamond', 'VS1 Clarity', 'F Color Grade'],
    rating: 4.9,
    reviews: 128,
    inStock: true,
    isBestseller: true,
  },
  {
    id: '2',
    name: 'Celestial Pearl Necklace',
    price: 2499,
    image: '/celestial-pearl-necklace.jpg',
    images: [
      '/celestial-pearl-necklace.jpg',
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80',
    ],
    category: 'Necklaces',
    collection: 'Celestial',
    description: 'Elegant South Sea pearl necklace with diamond accents on a delicate gold chain.',
    details: ['18k Yellow Gold', 'South Sea Pearls', 'Diamond Accents', '18-inch Chain'],
    rating: 4.8,
    reviews: 94,
    inStock: true,
    isNew: true,
  },
  {
    id: '3',
    name: 'Royal Sapphire Earrings',
    price: 3299,
    image: '/royal-sapphire-earrings.jpg',
    images: [
      '/royal-sapphire-earrings.jpg',
    ],
    category: 'Earrings',
    collection: 'Royal',
    description: 'Magnificent blue sapphire drop earrings surrounded by a halo of brilliant diamonds.',
    details: ['18k White Gold', '2 Carat Sapphires', 'Diamond Halo', 'Push Back Closure'],
    rating: 4.9,
    reviews: 76,
    inStock: true,
    isBestseller: true,
  },
  {
    id: '4',
    name: 'Ocean Wave Bracelet',
    price: 1899,
    originalPrice: 2299,
    image: '/ocean-wave-bracelet.jpg',
    images: [
      '/ocean-wave-bracelet.jpg',
    ],
    category: 'Bracelets',
    collection: 'Ocean',
    description: 'Flowing wave-inspired bracelet crafted in rose gold with aquamarine gemstones.',
    details: ['14k Rose Gold', 'Aquamarine Stones', 'Adjustable Clasp', '7-inch Length'],
    rating: 4.7,
    reviews: 52,
    inStock: true,
    isNew: true,
  },
  {
    id: '5',
    name: 'Eternal Love Band',
    price: 1499,
    image: '/eternal-love-band.jpg',
    images: [
      '/eternal-love-band.jpg',
    ],
    category: 'Rings',
    collection: 'Eternal',
    description: 'Classic eternity band featuring a continuous line of brilliant-cut diamonds.',
    details: ['Platinum', '0.5 Carat Total', 'Full Eternity', 'Comfort Fit'],
    rating: 4.8,
    reviews: 167,
    inStock: true,
  },
  {
    id: '6',
    name: 'Celestial Star Pendant',
    price: 899,
    image: '/celestial-star-pendant.jpg',
    images: [
      '/celestial-star-pendant.jpg',
    ],
    category: 'Necklaces',
    collection: 'Celestial',
    description: 'Delicate star-shaped pendant with a central diamond on a fine cable chain.',
    details: ['14k Yellow Gold', '0.25 Carat Diamond', '16-18 inch Chain', 'Lobster Clasp'],
    rating: 4.6,
    reviews: 89,
    inStock: true,
  },
  {
    id: '7',
    name: 'Royal Crown Ring',
    price: 5999,
    image: 'https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?w=800&q=80',
    ],
    category: 'Rings',
    collection: 'Royal',
    description: 'Majestic crown-inspired ring featuring rubies and diamonds in a regal setting.',
    details: ['18k Yellow Gold', 'Natural Rubies', 'Diamond Accents', 'Crown Design'],
    rating: 5.0,
    reviews: 43,
    inStock: true,
    isBestseller: true,
  },
  {
    id: '8',
    name: 'Ocean Pearl Studs',
    price: 699,
    originalPrice: 899,
    image: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=800&q=80',
    ],
    category: 'Earrings',
    collection: 'Ocean',
    description: 'Classic freshwater pearl stud earrings with secure screw-back posts.',
    details: ['14k White Gold', '8mm Pearls', 'AAA Quality', 'Screw Back'],
    rating: 4.7,
    reviews: 234,
    inStock: true,
  },
  {
    id: '9',
    name: 'Eternal Diamond Tennis Bracelet',
    price: 7999,
    image: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=800&q=80',
    ],
    category: 'Bracelets',
    collection: 'Eternal',
    description: 'Timeless tennis bracelet with perfectly matched round brilliant diamonds.',
    details: ['18k White Gold', '5 Carat Total', 'VS Clarity', 'Box Clasp with Safety'],
    rating: 4.9,
    reviews: 67,
    inStock: true,
    isBestseller: true,
  },
  {
    id: '10',
    name: 'Celestial Moon Earrings',
    price: 1299,
    image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&q=80',
    ],
    category: 'Earrings',
    collection: 'Celestial',
    description: 'Crescent moon drop earrings with moonstone centers and diamond details.',
    details: ['14k White Gold', 'Natural Moonstone', 'Diamond Accents', 'French Wire'],
    rating: 4.8,
    reviews: 56,
    inStock: true,
    isNew: true,
  },
  {
    id: '11',
    name: 'Royal Emerald Pendant',
    price: 4499,
    image: '/royal-emerald-pendant.jpg',
    images: [
      '/royal-emerald-pendant.jpg',
    ],
    category: 'Necklaces',
    collection: 'Royal',
    description: 'Stunning Colombian emerald pendant with a diamond-studded bail on gold chain.',
    details: ['18k Yellow Gold', '2 Carat Emerald', 'Diamond Bail', '20-inch Chain'],
    rating: 4.9,
    reviews: 38,
    inStock: true,
  },
  {
    id: '12',
    name: 'Ocean Coral Cuff',
    price: 2199,
    image: '/ocean-coral-cuff.jpg',
    images: [
      '/ocean-coral-cuff.jpg',
    ],
    category: 'Bracelets',
    collection: 'Ocean',
    description: 'Organic coral-inspired cuff bracelet in rose gold with diamond sea life motifs.',
    details: ['14k Rose Gold', 'Diamond Accents', 'Open Cuff Design', 'Adjustable'],
    rating: 4.6,
    reviews: 29,
    inStock: true,
    isNew: true,
  },
  {
    id: '13',
    name: 'Ocean Aqua Necklace',
    price: 1799,
    image: '/ocean-aqua-necklace.jpg',
    images: ['/ocean-aqua-necklace.jpg'],
    category: 'Necklaces',
    collection: 'Ocean',
    description: 'Delicate aquamarine pendant on a rose gold chain, inspired by deep ocean hues.',
    details: ['14k Rose Gold', 'Aquamarine Pendant', '18-inch Chain', 'Lobster Clasp'],
    rating: 4.7,
    reviews: 41,
    inStock: true,
    isNew: true,
  },
  {
    id: '14',
    name: 'Celestial Moon Ring',
    price: 1299,
    image: '/celestial-moon-ring.png',
    images: ['/celestial-moon-ring.png'],
    category: 'Rings',
    collection: 'Celestial',
    description: 'Crescent moon ring set with pavé diamonds in 14k white gold.',
    details: ['14k White Gold', 'Pavé Diamonds', 'Moon Motif', 'Comfort Fit'],
    rating: 4.8,
    reviews: 55,
    inStock: true,
  },
  {
    id: '15',
    name: 'Royal Pearl Earrings',
    price: 2799,
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80'],
    category: 'Earrings',
    collection: 'Royal',
    description: 'Lustrous South Sea pearl drop earrings framed in 18k gold with diamond accents.',
    details: ['18k Yellow Gold', 'South Sea Pearls', 'Diamond Accents', 'Push-Back Closure'],
    rating: 4.9,
    reviews: 33,
    inStock: true,
    isBestseller: true,
  },
  // Eternal — Rings (Under $1k)
  {
    id: '16',
    name: 'Eternal Promise Band',
    price: 799,
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&q=80'],
    category: 'Rings',
    collection: 'Eternal',
    description: 'A delicate promise ring in sterling silver with a single brilliant-cut diamond.',
    details: ['Sterling Silver', '0.15 Carat Diamond', 'Comfort Fit', 'Polished Finish'],
    rating: 4.6, reviews: 88, inStock: true,
  },
  // Celestial — Rings (Under $1k)
  {
    id: '17',
    name: 'Celestial Stardust Ring',
    price: 649,
    image: '/celestial-stardust-ring.jpg',
    images: ['/celestial-stardust-ring.jpg'],
    category: 'Rings',
    collection: 'Celestial',
    description: 'Delicate stardust ring with pavé diamond stars on a slender gold band.',
    details: ['14k Gold', 'Pavé Diamond Stars', 'Stackable', 'Sizes 4–9'],
    rating: 4.7, reviews: 62, inStock: true, isNew: true,
  },
  // Celestial — Rings ($1k–$3k)
  {
    id: '18',
    name: 'Celestial Galaxy Ring',
    price: 2199,
    image: 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=800&q=80'],
    category: 'Rings',
    collection: 'Celestial',
    description: 'Bold statement ring with a midnight sapphire center and diamond constellation halo.',
    details: ['18k White Gold', '1.2 Carat Sapphire', 'Diamond Halo', 'Rhodium Plated'],
    rating: 4.8, reviews: 47, inStock: true,
  },
  // Ocean — Rings
  {
    id: '19',
    name: 'Ocean Tide Ring',
    price: 1399,
    image: '/ocean-tide-ring.jpg',
    images: ['/ocean-tide-ring.jpg'],
    category: 'Rings',
    collection: 'Ocean',
    description: 'Fluid wave-shaped ring in rose gold with graduated aquamarine stones.',
    details: ['14k Rose Gold', 'Aquamarine Stones', 'Wave Design', 'Polished Finish'],
    rating: 4.6, reviews: 39, inStock: true, isNew: true,
  },
  // Ocean — Earrings (Under $1k)
  {
    id: '20',
    name: 'Ocean Breeze Studs',
    price: 549,
    image: '/ocean-breeze-studs.png',
    images: ['/ocean-breeze-studs.png'],
    category: 'Earrings',
    collection: 'Ocean',
    description: 'Dainty sea-foam inspired stud earrings with light blue topaz in rose gold.',
    details: ['14k Rose Gold', 'Blue Topaz', 'Stud Style', 'Push-Back Closure'],
    rating: 4.5, reviews: 71, inStock: true,
  },
  // Eternal — Earrings
  {
    id: '21',
    name: 'Eternal Diamond Drops',
    price: 2899,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80'],
    category: 'Earrings',
    collection: 'Eternal',
    description: 'Classic teardrop diamond earrings in 18k white gold — the ultimate timeless gift.',
    details: ['18k White Gold', '0.8 Carat Total', 'Teardrop Silhouette', 'Lever Back'],
    rating: 4.9, reviews: 52, inStock: true, isBestseller: true,
  },
  // Celestial — Necklaces (Over $5k)
  {
    id: '22',
    name: 'Celestial Aurora Necklace',
    price: 6299,
    image: '/celestial-aurora-necklace.jpg',
    images: ['/celestial-aurora-necklace.jpg'],
    category: 'Necklaces',
    collection: 'Celestial',
    description: 'Grand celestial necklace with diamond-set moon phases on an 18k gold chain.',
    details: ['18k Yellow Gold', '2.5 Carat Diamonds', 'Moon Phase Motif', '18-inch Chain'],
    rating: 5.0, reviews: 18, inStock: true, isBestseller: true,
  },
  // Royal — Rings (Over $5k)
  {
    id: '23',
    name: 'Royal Coronation Ring',
    price: 8499,
    image: '/royal-coronation-ring.png',
    images: ['/royal-coronation-ring.png'],
    category: 'Rings',
    collection: 'Royal',
    description: 'Magnificent ruby and diamond coronation ring in 18k gold — fit for royalty.',
    details: ['18k Yellow Gold', '3 Carat Ruby', 'Diamond Surround', 'Heirloom Quality'],
    rating: 5.0, reviews: 12, inStock: true,
  },
  // Eternal — Necklaces
  {
    id: '24',
    name: 'Eternal Solitaire Necklace',
    price: 3599,
    image: 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=800&q=80'],
    category: 'Necklaces',
    collection: 'Eternal',
    description: 'A single brilliant diamond suspended on a fine platinum chain — eternally elegant.',
    details: ['Platinum', '0.75 Carat Diamond', 'Box Chain', '16–18 inch Adjustable'],
    rating: 4.9, reviews: 66, inStock: true, isBestseller: true,
  },
  // Celestial — Bracelets
  {
    id: '26',
    name: 'Celestial Star Chain Bracelet',
    price: 1199,
    image: '/celestial-star-chain-bracelet.jpg',
    images: ['/celestial-star-chain-bracelet.jpg'],
    category: 'Bracelets',
    collection: 'Celestial',
    description: 'A delicate star-link chain bracelet with diamond-tipped points in 14k gold.',
    details: ['14k White Gold', 'Diamond Stars', 'Chain Link', 'Lobster Clasp'],
    rating: 4.7, reviews: 43, inStock: true, isNew: true,
  },
  // Ocean — Necklaces ($3,000–$5,000)
  {
    id: '27',
    name: 'Ocean Sapphire Cascade Necklace',
    price: 3799,
    image: '/ocean-sapphire-cascade-necklace.png',
    images: ['/ocean-sapphire-cascade-necklace.png'],
    category: 'Necklaces',
    collection: 'Ocean',
    description: 'A cascading ocean-blue sapphire necklace in 18k white gold, evoking the depth of the sea.',
    details: ['18k White Gold', 'Blue Sapphires', 'Diamond Accents', '18-inch Chain'],
    rating: 4.8, reviews: 31, inStock: true,
  },
  // Ocean — Necklaces (Over $5,000)
  {
    id: '28',
    name: 'Ocean Grand Pearl Rivière',
    price: 6499,
    image: '/ocean-grand-pearl-riviere.jpg',
    images: ['/ocean-grand-pearl-riviere.jpg'],
    category: 'Necklaces',
    collection: 'Ocean',
    description: 'A grand South Sea pearl rivière necklace with a diamond-encrusted 18k gold clasp, inspired by ocean depths.',
    details: ['18k White Gold', 'South Sea Pearls', 'Diamond Clasp', '20-inch'],
    rating: 5.0, reviews: 14, inStock: true, isBestseller: true,
  },
  // Eternal — Necklaces (Over $5,000)
  {
    id: '29',
    name: 'Eternal Diamond Rivière Necklace',
    price: 9999,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80'],
    category: 'Necklaces',
    collection: 'Eternal',
    description: 'An extraordinary diamond rivière necklace with 5 carats of perfectly matched round brilliants in platinum.',
    details: ['Platinum', '5 Carat Total', 'Round Brilliant Diamonds', '16-inch'],
    rating: 5.0, reviews: 9, inStock: true, isBestseller: true,
  },
  // Royal — Necklaces (Over $5,000)
  {
    id: '30',
    name: 'Royal Ruby Collar Necklace',
    price: 11500,
    image: '/royal-ruby-collar-necklace.jpg',
    images: ['/royal-ruby-collar-necklace.jpg'],
    category: 'Necklaces',
    collection: 'Royal',
    description: 'A magnificent Burmese ruby and diamond collar necklace set in 18k yellow gold — a true heirloom.',
    details: ['18k Yellow Gold', 'Burmese Rubies', 'Diamond Surround', 'Collar Style'],
    rating: 5.0, reviews: 7, inStock: true,
  },
  // Royal — Earrings (Over $5,000)
  {
    id: '31',
    name: 'Royal Chandelier Diamond Earrings',
    price: 7200,
    image: '/royal-chandelier-earrings.jpg',
    images: ['/royal-chandelier-earrings.jpg'],
    category: 'Earrings',
    collection: 'Royal',
    description: 'Opulent chandelier earrings with cascading diamonds and deep blue sapphires in 18k white gold.',
    details: ['18k White Gold', 'Sapphires & Diamonds', 'Chandelier Style', 'Lever Back'],
    rating: 4.9, reviews: 19, inStock: true, isBestseller: true,
  },
  // Royal — Bracelets (Under $1,000)
  {
    id: '32',
    name: 'Royal Gold Charm Bracelet',
    price: 749,
    image: '/royal-gold-charm-bracelet.jpg',
    images: ['/royal-gold-charm-bracelet.jpg'],
    category: 'Bracelets',
    collection: 'Royal',
    description: 'A dainty 14k gold charm bracelet adorned with royal insignia — perfect for everyday luxury.',
    details: ['14k Yellow Gold', 'Royal Charm Motifs', 'Lobster Clasp', '7-inch Length'],
    rating: 4.6, reviews: 55, inStock: true,
  },
  // Royal — Bracelets ($1,000–$3,000)
  {
    id: '33',
    name: 'Royal Sapphire Tennis Bracelet',
    price: 2499,
    image: '/royal-sapphire-tennis-bracelet.jpg',
    images: ['/royal-sapphire-tennis-bracelet.jpg'],
    category: 'Bracelets',
    collection: 'Royal',
    description: 'A regal sapphire and diamond tennis bracelet set in 18k white gold, fit for royalty.',
    details: ['18k White Gold', 'Blue Sapphires', 'Diamond Accents', 'Box Clasp'],
    rating: 4.8, reviews: 28, inStock: true,
  },
  // Eternal — Bracelets ($3k–$5k)
  {
    id: '35',
    name: 'Eternal Diamond Link Bracelet',
    price: 3899,
    image: '/eternal-diamond-link-bracelet.png',
    images: ['/eternal-diamond-link-bracelet.png'],
    category: 'Bracelets',
    collection: 'Eternal',
    description: 'An exquisite diamond link bracelet in 18k white gold, each link pavé-set with brilliant-cut diamonds for continuous sparkle.',
    details: ['18k White Gold', '2 Carat Total', 'Pavé Diamond Links', 'Box Clasp with Safety'],
    rating: 4.9, reviews: 21, inStock: true, isBestseller: true,
  },
  // Celestial — Bracelets ($3k–$5k)
  {
    id: '36',
    name: 'Celestial Moonstone Cuff',
    price: 3299,
    image: 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=800&q=80'],
    category: 'Bracelets',
    collection: 'Celestial',
    description: 'A sculptural cuff bracelet featuring luminous moonstones and pavé diamonds set in 18k yellow gold — inspired by the phases of the moon.',
    details: ['18k Yellow Gold', 'Natural Moonstones', 'Diamond Accents', 'Open Cuff'],
    rating: 4.8, reviews: 17, inStock: true, isNew: true,
  },
]

export const collections = [
  {
    id: 'eternal',
    name: 'Eternal Collection',
    slug: 'eternal',
    description: 'Timeless pieces that celebrate everlasting love and commitment.',
    image: '/eternal-collection-cover.jpg',
  },
  {
    id: 'celestial',
    name: 'Celestial Collection',
    slug: 'celestial',
    description: 'Inspired by the stars and moon, for those who dream beyond.',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80',
  },
  {
    id: 'ocean',
    name: 'Ocean Collection',
    slug: 'ocean',
    description: 'Flowing designs inspired by the beauty and mystery of the sea.',
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&q=80',
  },
  {
    id: 'royal',
    name: 'Royal Collection',
    slug: 'royal',
    description: 'Regal pieces fit for royalty, featuring precious gemstones.',
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80',
  },
]

export const categories = ['All', 'Rings', 'Necklaces', 'Earrings', 'Bracelets']

export const getProductById = (id: string): Product | undefined => {
  return products.find((product) => product.id === id)
}

export const getProductsByCategory = (category: string): Product[] => {
  if (category === 'All') return products
  return products.filter((product) => product.category === category)
}

export const getProductsByCollection = (collection: string): Product[] => {
  return products.filter((product) => product.collection.toLowerCase() === collection.toLowerCase())
}

export const getFeaturedProducts = (): Product[] => {
  return products.filter((product) => product.isBestseller || product.isNew).slice(0, 4)
}

export const searchProducts = (query: string): Product[] => {
  const lowercaseQuery = query.toLowerCase()
  return products.filter(
    (product) =>
      product.name.toLowerCase().includes(lowercaseQuery) ||
      product.category.toLowerCase().includes(lowercaseQuery) ||
      product.collection.toLowerCase().includes(lowercaseQuery) ||
      product.description.toLowerCase().includes(lowercaseQuery)
  )
}
